/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 05660bb69fadecebec4e3b1a09c1f0cd)
declare namespace Cloudflare {
	interface Env {
		PAGEDATA_CACHE: KVNamespace;
		STATIC_CACHE: KVNamespace;
		AGENTS_CHATSTORE: string;
		RWSDK_CHATSTORE: string;
		WEBSOCKET_AGENT_NAME: string;
		GH_OWNER: string;
		GH_REPO: string;
		GH_BRANCH: string;
		GH_PATH: string;
		DEV_CONTENT_DIR: string;
		OPENAI_API_KEY: string;
		GH_PAT: string;
		IMAGE_KEY: string;
		GH_TEST: string;
		CHATSTORE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatDurableObject>;
		WEBSOCKET_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").WebsocketAgent>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENTS_CHATSTORE" | "RWSDK_CHATSTORE" | "WEBSOCKET_AGENT_NAME" | "GH_OWNER" | "GH_REPO" | "GH_BRANCH" | "GH_PATH" | "DEV_CONTENT_DIR" | "OPENAI_API_KEY" | "GH_PAT" | "IMAGE_KEY" | "GH_TEST">> {}
}
