/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 08b81a534c8ada4cd2edea119c8b39ae)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "RealtimeDurableObject" | "ChatDurableObject" | "WebsocketAgent" | "ChatAgentSDKDO" | "ChatAgentAgentDO";
	}
	interface Env {
		PAGEDATA_CACHE: KVNamespace;
		STATIC_CACHE: KVNamespace;
		AGENTS_CHATSTORE: string;
		RWSDK_CHATSTORE: string;
		REALTIME_KEY: string;
		WEBSOCKET_AGENT_NAME: string;
		GH_OWNER: string;
		GH_REPO: string;
		GH_BRANCH: string;
		GH_PATH: string;
		DEV_CONTENT_DIR: string;
		THROTTLE_UPDATES_MS: number;
		OPENAI_API_KEY: string;
		GH_PAT: string;
		GH_TEST: string;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		CHATSTORE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatDurableObject>;
		WEBSOCKET_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").WebsocketAgent>;
		CHAT_AGENT_SDK_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatAgentSDKDO>;
		CHAT_AGENT_AGENT_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatAgentAgentDO>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENTS_CHATSTORE" | "RWSDK_CHATSTORE" | "REALTIME_KEY" | "WEBSOCKET_AGENT_NAME" | "GH_OWNER" | "GH_REPO" | "GH_BRANCH" | "GH_PATH" | "DEV_CONTENT_DIR" | "THROTTLE_UPDATES_MS" | "OPENAI_API_KEY" | "GH_PAT" | "GH_TEST">> {}
}
